### PR TITLE
Cached records refresh

### PR DESCRIPTION
**Pull request by JindrichSusen**

### CODE REVIEW

**Review by tvavrda — COMMENTED** [review]
So how does the original problem relate to screen being dirty? It is not clear from the code logic.

**Comment by tvavrda** [comment]
Why CRUDResult then does not add the record to the cache? The sole purpose of `UpdateObject` or `CreateObject` call is to deliver the new row back to the client. There is no need to call `getData` anymore since we already received it.

**Comment by ptomask** [comment]
> 
> 
> Why then CRUDResult does not add the record to the cache? The sole purpose of `UpdateObject` or `CreateObject` call is to deliver the new row back to the client. There is no need to call `getData` anymore since we already received it.

`getData` was originally called each time a selected parent row changed. Then we probably had too many `getData` calls too often so there was a cache added which returns results of the `getData` calls which we already know. You perform `CreateObject` which returns the new row and puts it to the grid, that is why it is visible for the first time, then you change parent row, which causes `getData` to be called internally, hitting the cache and returning the old data without the newly added row. 

Why? Well, because... It is a bug 🙈 But I would not say *"The bug is that we do not put `...Result` to the cache"*, I would rather say *"The bug is we retain the whole cache content for too long."* (If debouncing the `getData` calls is its only purpose)

**Comment by tvavrda** [comment]
Maybe the concept of _cache_ here is not appropriate. The client gets always all the data updates. So once we ask for the records we can keep them until the form closes since the only place the data get updated is the client. The goal is to reduce roundtrips. The current solution produces more roundtrips so I consider that bad.

**Review by tvavrda — CHANGES_REQUESTED** [review]
We should improve the system not to "cache" the data but to keep them forever until not needed anymore. When  child data are received they are always valid because the client does all the changes. So anything returned by calling `CreateObject`, `UpdateObject` or `DeleteObject` should update the data on the client. Only when master record changes it should be released. It seems to work this way on non-lazy-loaded screens. The only difference of lazy to non-lazy-loaded screens is that the child records get released when master record changes.

**Pull request merged**
